#!/bin/bash

sudo update-alternatives --set java /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
sudo update-alternatives --set javac /usr/lib/jvm/java-7-openjdk-amd64/bin/javac

# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system/cm-13.0
ANDROID_DEVICE=awifi
# Path to ccache dir
export USE_CCACHE=1
export CCACHE_COMPRESS=1
export CCACHE_DIR=~/android/system/.ccache
## End Edit

cd "$CM_PROJECT_DIR"
prebuilts/misc/linux-x86/ccache/ccache -z
source build/envsetup.sh
brunch "$ANDROID_DEVICE"
prebuilts/misc/linux-x86/ccache/ccache -s
