#!/bin/bash

sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac

# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system/cm-14.1
# Set device
ANDROID_DEVICE=gts210vewifi
# Enable SU by default
export WITH_SU=true
# Enable ccache
export USE_CCACHE=1
# enable ccache compression
export CCACHE_COMPRESS=1
# Path to ccache dir
export CCACHE_DIR=~/android/system/.ccache
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g"
# Fix Flex for Ubuntu 18.04
export LC_ALL=C
## End Edit

cd "$CM_PROJECT_DIR"
prebuilts/misc/linux-x86/ccache/ccache -z
source build/envsetup.sh
lunch lineage_"$ANDROID_DEVICE"-userdebug
mka bootimage
prebuilts/misc/linux-x86/ccache/ccache -s
