#!/bin/bash

sudo update-java-alternatives -s java-6-oracle

# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system/cm-11.0
# Set device
ANDROID_DEVICE=p3110
# Enable ccache
export USE_CCACHE=1
# Path to ccache dir
export CCACHE_DIR=~/android/system/.ccache-cm11
# Fix Flex for Ubuntu 18.04
export LC_ALL=C
## End Edit

cd "$CM_PROJECT_DIR"
prebuilts/misc/linux-x86/ccache/ccache -z
source build/envsetup.sh
lunch cm_"$ANDROID_DEVICE"-userdebug
mka bootzip
prebuilts/misc/linux-x86/ccache/ccache -s

sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
