#!/bin/bash

sudo update-java-alternatives -s java-1.7.0-openjdk-amd64
java -version
javac -version

# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system/cm-13.0
ANDROID_DEVICE=awifi
# Path to ccache dir
export USE_CCACHE=1
export CCACHE_COMPRESS=1
export CCACHE_DIR=~/android/system/.ccache
# Fix Flex for Ubuntu 18.04
export LC_ALL=C
## End Edit

cd "$CM_PROJECT_DIR"
prebuilts/misc/linux-x86/ccache/ccache -z
source build/envsetup.sh
brunch "$ANDROID_DEVICE"
prebuilts/misc/linux-x86/ccache/ccache -s

echo "Returning back to default Java configuration"
sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
java -version
javac -version
echo "Done."
