#!/bin/bash

sudo update-java-alternatives -s java-1.8.0-openjdk-amd64

# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system/lineage-15.1
# Set device
ANDROID_DEVICE=gts210vewifi
# Enable SU by default
export WITH_SU=true
# Enable ccache
export USE_CCACHE=1
# enable ccache compression
export CCACHE_COMPRESS=1
# Path to ccache dir
export CCACHE_DIR=~/T5/android/system/.ccache-15
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g"
# Fix Flex for Ubuntu 18.04
export LC_ALL=C
## End Edit

cd "$CM_PROJECT_DIR"
prebuilts/misc/linux-x86/ccache/ccache -z
source build/envsetup.sh
brunch "$ANDROID_DEVICE"
prebuilts/misc/linux-x86/ccache/ccache -s
