#!/bin/bash

# Path to root of OmniROM project directory
CM_PROJECT_DIR=~/android/system/android-6.0
ANDROID_DEVICE=v500
# Path to ccache dir
export USE_CCACHE=1
export CCACHE_DIR=~/android/system/.ccache
## End Edit

cd "$CM_PROJECT_DIR"
source build/envsetup.sh
make clean
