#!/bin/bash

# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system/cm-14.1
# Set device
ANDROID_DEVICE=gts210vewifi
# Enable SU by default
export WITH_SU=true
# Enable ccache
export USE_CCACHE=1
# enable ccache compression
export CCACHE_COMPRESS=1
# Path to ccache dir
export CCACHE_DIR=~/android/system/.ccache
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g"
## End Edit

cd "$CM_PROJECT_DIR"
source build/envsetup.sh
make clean

if [ -e kernel/samsung/msm8976/net/wireguard/crypto/zinc/chacha20/chacha20-arm64.S ]; then
   rm kernel/samsung/msm8976/net/wireguard/crypto/zinc/chacha20/chacha20-arm64.S
fi

if [ -e kernel/samsung/msm8976/net/wireguard/crypto/zinc/poly1305/poly1305-arm64.S ]; then
   rm kernel/samsung/msm8976/net/wireguard/crypto/zinc/poly1305/poly1305-arm64.S
fi
