#!/bin/bash

# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system/lineage-15.0
# Set device
ANDROID_DEVICE=gts210vewifi
# Enable SU by default
export WITH_SU=true
# Enable ccache
export USE_CCACHE=1
# Path to ccache dir
export CCACHE_DIR=~/T5/android/system/.ccache-15
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g"
## End Edit

cd "$CM_PROJECT_DIR"
source build/envsetup.sh
make clean
