#!/bin/bash

# Path to root of OmniROM project directory
CM_PROJECT_DIR=~/android/system/android-7.1
ANDROID_DEVICE=gts210vewifi
# Path to ccache dir
export USE_CCACHE=1
export CCACHE_COMPRESS=1
export CCACHE_DIR=~/android/system/.ccache
# Fix Flex for Ubuntu 18.04
export LC_ALL=C
## End Edit

cd "$CM_PROJECT_DIR"
source build/envsetup.sh
make clean
