#!/bin/bash

# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system/cm-13.0
ANDROID_DEVICE=awifi
# Path to ccache dir
export USE_CCACHE=1
export CCACHE_DIR=~/android/system/.ccache
## End Edit

cd "$CM_PROJECT_DIR"
source build/envsetup.sh
make clean
