#!/bin/bash

# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system/cm-14.1
# Set device
ANDROID_DEVICE=v500
# Enable SU by default
export WITH_SU=true
# Enable ccache
export USE_CCACHE=1
# Path to ccache dir
export CCACHE_DIR=~/android/system/.ccache
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g"
## End Edit

cd "$CM_PROJECT_DIR"
source build/envsetup.sh
make clean
