#!/bin/bash

# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system/cm-14.1
# Path to kernel directory
KERNEL_DIR=~/android/system/cm-14.1/kernel/samsung/msm8976
# Set device
ANDROID_DEVICE=gts210vewifi
# Enable SU by default
export WITH_SU=true
# Enable ccache
export USE_CCACHE=1
# enable ccache compression
export CCACHE_COMPRESS=1
# Path to ccache dir
export CCACHE_DIR=~/android/system/.ccache
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g"
# Fix Flex for Ubuntu 18.04
export LC_ALL=C
## End Edit

cd "$CM_PROJECT_DIR"
source build/envsetup.sh
make clean

echo "Cleaning kernel sources."
cd "$KERNEL_DIR"
make mrproper
