#!/bin/bash

CHANGE_FILE=~/android/changelog.html
CM_PROJECT_DIR=~/android/system
## End Edit

NOW=$(date +"%a %B %d %r %Y")

if [ ! -d "$CM_PROJECT_DIR" ]; then
  echo "The root of your CyanogenMod project source directory is not found. Exiting!"
  exit
fi

REPOS=$(find "$CM_PROJECT_DIR" -name .git -type d -exec dirname {} \; | sort)

cd "$CM_PROJECT_DIR"
DIR_LEN=$(pwd)

rm "$CHANGE_FILE"
touch "$CHANGE_FILE"

echo "<!DOCTYPE html><html><body><pre><u>Since $NOW</u><br>" > "$CHANGE_FILE"

for REPOLINE in $REPOS ; do
    REPOPATH=$(echo $REPOLINE | cut -c $((${#DIR_LEN} + 2))-)
    if [ ! "$REPOPATH" == "" ] && [ ! "$REPOPATH" == ".repo/manifests" ]; then
      if [ -d "$CM_PROJECT_DIR"/"$REPOPATH" ]; then
        cd "$CM_PROJECT_DIR"/"$REPOPATH"
        GITOUT=$(git log HEAD --pretty="%h (%cr) %s" --since="5 days ago")
        if [ ! "$GITOUT" == "" ]; then
          echo "<b>$REPOPATH</b>" >> "$CHANGE_FILE"
          echo "$GITOUT<br>" >> "$CHANGE_FILE"
        fi
      fi
    fi
done

echo "</pre></body></html>" >> "$CHANGE_FILE"

echo ""
echo "Most recent changes:"
echo ""
cat "$CHANGE_FILE" | grep -E 'hours ago|minutes ago' | sed 's/<br>//g'
echo ""
