#!/bin/bash

# Path to changelog file
CHANGE_FILE=~/android/changelog.html
# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system
# Paths to Android manifests
FILE1=$CM_PROJECT_DIR/.repo/manifests/default.xml
FILE2=$CM_PROJECT_DIR/.repo/manifests/snippets/hal_cm_all.xml
FILE3=$CM_PROJECT_DIR/.repo/local_manifests/local_manifests.xml
## End Edit

NOW=$(date +"%a %B %d %r %Y")

if [ ! -d "$CM_PROJECT_DIR" ]; then
  echo "The root of your CyanogenMod project source directory is not found. Exiting!"
  exit
fi

if [ -e "$FILE1" ]; then
  REPOS=$(cat $FILE1)
fi

if [ -e "$FILE2" ]; then
  REPOS+=$(cat $FILE2)
fi

if [ -e "$FILE3" ]; then
  REPOS+=$(cat $FILE3)
fi

REPOS=$(echo "$REPOS" | sort)

rm "$CHANGE_FILE"
touch "$CHANGE_FILE"

echo "<!DOCTYPE html><html><body><pre><u>Since $NOW</u><br>" > "$CHANGE_FILE"

for REPOLINE in $REPOS ; do
    REPOPATH=$(echo "$REPOLINE" | grep "path=" | cut -d"\"" -f2)
    if [ ! "$REPOPATH" == "" ]; then
      if [ -d "$CM_PROJECT_DIR"/"$REPOPATH" ]; then
        cd "$CM_PROJECT_DIR"/"$REPOPATH"
        GITOUT=$(git log HEAD --pretty="%h (%cr) %s" --since="5 days ago")
        if [ ! "$GITOUT" == "" ]; then
          echo "<b>$REPOPATH</b>" >> "$CHANGE_FILE"
          echo "$GITOUT<br>" >> "$CHANGE_FILE"
        fi
      fi
    fi
done

echo "</pre></body></html>" >> "$CHANGE_FILE"

echo ""
echo "Most recent changes:"
echo ""
cat "$CHANGE_FILE" | grep -E 'hours ago|minutes ago|seconds ago' | sed 's/<br>//g'
echo ""
