#!/bin/bash

# Path to changelog file
CHANGE_FILE=~/android/changelog-omni.html
# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system/android-6.0
## End Edit

PROJECT_LIST=$CM_PROJECT_DIR/.repo/project.list

NOW=$(date -u)

if [ -e "$PROJECT_LIST" ]; then
  REPOS=$(cat "$PROJECT_LIST" | sort)
else
  echo "Project list not found. Run repo_sync command to generate project list. Exiting!"
  exit
fi

rm "$CHANGE_FILE"

echo "<!DOCTYPE html><html><body><h2><b><u>Since $NOW</u></b></h2><br>" > "$CHANGE_FILE"

for REPOPATH in $REPOS ; do
    if [ ! "$REPOPATH" == "" ]; then
      if [ -d "$CM_PROJECT_DIR"/"$REPOPATH" ]; then
        cd "$CM_PROJECT_DIR"/"$REPOPATH"
        GITOUT=$(git log HEAD --pretty="<li>%h (%cr) %s (%an)</li>" --since="3 weeks ago")
        if [ ! "$GITOUT" == "" ]; then
          echo "<font size="4"><b>$REPOPATH</b></font>" >> "$CHANGE_FILE"
          echo '<ul style="list-style-type:square">' >> "$CHANGE_FILE"
          echo "$GITOUT" >> "$CHANGE_FILE"
          echo "</ul>" >> "$CHANGE_FILE"
        fi
      fi
    fi
done

echo "</body></html>" >> "$CHANGE_FILE"

echo ""
echo "Most recent changes:"
echo ""
cat "$CHANGE_FILE" | grep -E 'hours ago|minutes ago|seconds ago' | sed 's/<br>//g' | sed 's/<\/li>//g' | sed 's/<li>//g'
echo ""
