#!/bin/bash

# Path to changelog file
CHANGE_FILE=~/android/changelog-cm11.txt
# Path to root of CM project directory
CM_PROJECT_DIR=~/android/cm11
## End Edit

PROJECT_LIST=$CM_PROJECT_DIR/.repo/project.list

NOW=$(date -u)

if [ -e "$PROJECT_LIST" ]; then
  REPOS=$(cat "$PROJECT_LIST" | sort)
else
  echo "Project list not found. Run repo_sync command to generate project list. Exiting!"
  exit
fi

rm "$CHANGE_FILE"

echo "Since $NOW" > "$CHANGE_FILE"
echo "" >> "$CHANGE_FILE"

for REPOPATH in $REPOS ; do
    if [ ! "$REPOPATH" == "" ]; then
      if [ -d "$CM_PROJECT_DIR"/"$REPOPATH" ]; then
        cd "$CM_PROJECT_DIR"/"$REPOPATH"
        GITOUT=$(git log HEAD --pretty="  * %h (%cr) %s (%an)" --since="6 weeks ago")
        if [ ! "$GITOUT" == "" ]; then
          echo "$REPOPATH" >> "$CHANGE_FILE"
          echo "$GITOUT" >> "$CHANGE_FILE"
          echo "" >> "$CHANGE_FILE"
        fi
      fi
    fi
done


echo ""
echo "Most recent changes:"
echo ""
cat "$CHANGE_FILE" | grep -E 'hours ago|minutes ago|seconds ago'
echo ""
