#!/bin/bash

# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system/cm-13.0
## End Edit

cd "$CM_PROJECT_DIR"

if [ -e "../../patches/build.name.diff" ]; then
  patch -R -p1 --no-backup-if-mismatch < ../../patches/build.name.diff
fi

repo sync --no-clone-bundle

if [ -e "../../patches/build.name.diff" ]; then
  echo "Setting build name to NIGHTLY"
  patch -p1 --no-backup-if-mismatch < ../../patches/build.name.diff
fi

echo ""

