#!/bin/bash

# Path to root of OmniROM project directory
CM_PROJECT_DIR=~/android/system/android-7.1
CM_RECOVERY="$CM_PROJECT_DIR"/bootable/recovery
CM_DEVICE="$CM_PROJECT_DIR"/device/samsung/gts210vewifi
## End Edit

cd "$CM_PROJECT_DIR"

repo sync --no-clone-bundle

echo ""

if [ -d "$CM_RECOVERY" ]; then
  cd "$CM_RECOVERY"
  echo "Rebasing recovery repo."
  git checkout android-7.1
  git fetch omnirom
  git rebase omnirom/android-7.1
  echo ""
fi

if [ -d "$CM_DEVICE" ]; then
  cd "$CM_DEVICE"
  echo "Rebasing device repo."
  git checkout android-7.1
  git fetch teamwin
  git rebase teamwin/android-7.1
  echo ""
fi
