#!/bin/bash

cd ~/android/system/android-6.0
export USE_CCACHE=1
export CCACHE_DIR=~/android/system/.ccache
## END EDIT ##

prebuilts/misc/linux-x86/ccache/ccache -M 15G
prebuilts/misc/linux-x86/ccache/ccache -s
