#!/bin/bash

#!/bin/bash
# Path to root of CM project directory
CM_PROJECT_DIR=~/android/system/cm-14.1
ANDROID_DEVICE=v500
# Path to ccache dir
export USE_CCACHE=1
export CCACHE_DIR=~/android/system/.ccache
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g"
## End Edit

cd "$CM_PROJECT_DIR"
prebuilts/misc/linux-x86/ccache/ccache -z
source build/envsetup.sh
make clean
brunch "$ANDROID_DEVICE"
prebuilts/misc/linux-x86/ccache/ccache -s
