#!/bin/bash

# Path to root of OmniROM project directory
CM_PROJECT_DIR=~/android/system/android-7.1
ANDROID_DEVICE=gts210vewifi
# Path to ccache dir
export USE_CCACHE=1
export CCACHE_DIR=~/android/system/.ccache
export TW_DEVICE_VERSION=1
## End Edit

cd "$CM_PROJECT_DIR"
prebuilts/misc/linux-x86/ccache/ccache -z
source build/envsetup.sh
make clean
lunch omni_$ANDROID_DEVICE-eng
mka recoveryimage
prebuilts/misc/linux-x86/ccache/ccache -s
