#!/bin/bash

## OTA Rest Server builds directory
BUILDDIR=/var/www/html/CyanogenModOTA/builds
## Root of CM project directory
PROJECT_DIR=~/android/cm11
## Changelog location
CHANGE_FILE=~/android/changelog-cm11.txt
## Device name
ANDROID_DEVICE=p3110
## End Edit

OUTDIR=$PROJECT_DIR/out/target/product/$ANDROID_DEVICE

## Find file name of ROM and set variable
cd "$OUTDIR"
FILE=$(ls cm-11-*.zip)

## Check if ROM exists before proceding
if [ ! -e "$FILE" ]; then
  echo "Build Failed!"
  if [ -e `which send_mail_cm11` ]; then
    echo ""
    echo "Automatic email notification sent for failed build!"
    SUBJECT="Build Failed!"
    send_mail_cm11 "$SUBJECT"
  fi
  exit
fi

echo "Build Successful!"
if [ -e `which send_mail_cm11` ]; then
  echo ""
  echo "Automatic email notification sent for successful build."
  SUBJECT="Build Successful for $FILE"
  send_mail_cm11 "$SUBJECT"
fi

## Remove extension of file name and set variable
NOEXT=${FILE%\.*}

echo ""
echo "Removing previous builds on OTA REST Server."
echo ""

rm "$BUILDDIR"/full/cm-11-*

echo "Copying ROM ($FILE) to OTA REST Server."
echo ""
cp "$FILE" "$BUILDDIR"/full/

if [ -e "$CHANGE_FILE" ]; then
  echo "Copying changelog ($NOEXT.txt) to OTA REST Server."
  echo ""
  cp "$CHANGE_FILE" "$BUILDDIR"/full/"$NOEXT".txt
else
  echo "Changelog not found!"
  echo ""
  exit
fi

echo ""
echo "Done."
echo ""
