#!/bin/bash

## Directory of Apache OTA Rest Server that contains builds
BUILDDIR="/var/www/html/CyanogenModOTA/builds"

## Change to targets build directory
cd ~/android/system/out/target/product/awifi
FILE=`ls cm-13*-awifi.zip`

## If zip is UNOFFICIAL then rename to NIGHTLY to fix OTA
FILE_NEW=`echo $FILE | sed 's/'UNOFFICIAL'/'NIGHTLY'/'`

## Remove extension of file name and set new variable
NOEXT=${FILE_NEW%\.*}

echo ""
echo "Removing previous builds on OTA REST Server."
echo ""

sudo mv "$BUILDDIR"/changelog/.gitignore "$BUILDDIR"/
sudo rm -rf "$BUILDDIR"/changelog
sudo mkdir "$BUILDDIR"/changelog
sudo mv "$BUILDDIR"/.gitignore "$BUILDDIR"/changelog/
sudo mv "$BUILDDIR"/full/.gitignore "$BUILDDIR"/
sudo rm -rf "$BUILDDIR"/full
sudo mkdir "$BUILDDIR"/full
sudo mv "$BUILDDIR"/.gitignore "$BUILDDIR"/full/

if [ -e "$FILE" ]; then
  echo "Copying ROM ($FILE_NEW) to OTA REST Server."
  sudo cp "$FILE" "$BUILDDIR"/full/"$FILE_NEW"
else
  echo "ROM not found"
  exit
fi

if [ -e ~/android/changelog.txt ]; then
  echo "Copying changelog ($NOEXT.txt) to OTA REST Server."
  sudo cp ~/android/changelog.txt "$BUILDDIR"/changelog/"$NOEXT".txt
else
  echo "Changelog not found"
  exit
fi

if [ -e `which oat_unit_test` ]; then
  echo ""
  echo "OTA Unit Test."
  echo ""
  ota_unit_test
fi

echo ""
echo "Done."
echo ""
