#!/bin/bash

## LineageOS server directory
OTA_DIR=~/android/system/lineageos_updater
## Document Root
DOC_DIR=/var/www/html
## Root of Rom directory in Document Root
ROM_DIR=CyanogenModOTA/builds/full
## Root of CM project directory
PROJECT_DIR=~/android/system/lineage-15.1
## Changelog location
CHANGE_FILE=~/android/changelog-lineage15.html
## Device name
ANDROID_DEVICE=gts210vewifi
## End Edit

OUTDIR=$PROJECT_DIR/out/target/product/$ANDROID_DEVICE

if [ ! -e "$OUTDIR" ]; then
  echo "No build detected. Exiting."
  exit
fi

## Find file name of ROM and set variable
cd "$OUTDIR"
FILE=$(ls lineage-15.1-*.zip)

## Check if ROM exists before proceding
if [ ! -e "$FILE" ]; then
  echo "Build Failed!"
  if [ -e `which send_mail_lineage15` ]; then
    echo ""
    echo "Automatic email notification sent for failed build!"
    SUBJECT="Build Failed!"
    send_mail_lineage15 "$SUBJECT"
    notify-send "$SUBJECT"
  fi
  exit
fi

echo "Build Successful!"
if [ -e `which send_mail_lineage15` ]; then
  echo ""
  echo "Automatic email notification sent for successful build."
  SUBJECT="Build Successful for $FILE"
  send_mail_lineage15 "$SUBJECT"
  notify-send "$SUBJECT"
fi

## Remove extension of file name and set variable
NOEXT=${FILE%\.*}

CHANGELOG="$NOEXT".html
MD5FILE="$FILE".md5sum
PROPFILE="$FILE".prop

cd "$DOC_DIR"/"$ROM_DIR"

echo ""
echo "Removing previous builds on OTA REST Server."
echo ""

rm lineage-15.1-*

echo "Copying ROM ($FILE) and MD5SUM ($MD5FILE) to OTA REST Server."
echo ""

cd "$OUTDIR"
cp "$FILE" "$DOC_DIR"/"$ROM_DIR"/
cp "$MD5FILE" "$DOC_DIR"/"$ROM_DIR"/
echo "Copying build.prop ($PROPFILE) to OTA REST Server."
echo ""
cp system/build.prop "$DOC_DIR"/"$ROM_DIR"/"$PROPFILE"

if [ -e "$CHANGE_FILE" ]; then
  echo "Copying changelog ($CHANGELOG) to OTA REST Server."
  echo ""
  cp "$CHANGE_FILE" "$DOC_DIR"/"$ROM_DIR"/"$CHANGELOG"
else
  echo "Changelog not found!"
  echo ""
  exit
fi

echo ""
echo "Done."
echo ""
